baseurl = "https://federico.barcelona"
title = "Federico Barcelona"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Federico Barcelona"
    description = "Federico Barcelona's personal website"
    keywords = "blog,developer,personal,devops"
    info = "DevOps & Cloud Security Software Engineer at Sysdig"
    avatarurl = "images/fede.jpg"
    #gravatar = "john.doe@example.com"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideFooter = true
    hideCredits = true
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "dark"

    # Hide the toggle button, along with the associated vertical divider
    hidecolorschemetoggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]
#    siteID = "ABCDE"
#    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
#[params.plausibleAnalytics]
#    domain = "example.com"
#    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
#[params.goatCounter]
#    code = "code"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/tembleking/"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab"
    weight = 2
    url = "https://gitlab.com/tembleking/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/tembleking/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/fede-barcelona/"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About me"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.es-es]
        languagename = "Español"
        title = "Federico Barcelona"

        [languages.es-es.params]
            info = "DevOps y Product Integration Engineer en Sysdig"
            description = "¡Bienvenido/a a mi página!"
            keywords = "blog,desarrollador,personal,devops"

        [languages.es-es.menu]

            [[languages.es-es.menu.main]]
            name = "Acerca de mi"
            weight = 1
            url = "about/"

            [[languages.es-es.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.es-es.menu.main]]
            name = "Proyectos"
            weight = 3
            url = "projects/"

            [[languages.es-es.menu.main]]
            name = "Contacto"
            weight = 5
            url = "contact/"

