baseurl: 'https://federico.barcelona'
title: Federico Barcelona
theme: hugo-coder
languagecode: en
defaultcontentlanguage: en
paginate: 20
pygmentsstyle: b2
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
# To enable comments in the website, uncomment this and add a shortname
#disqusShortname: "yourdiscussshortname"
markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    hl_Lines: ''
    lineAnchors: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    noHl: false
    style: dracula
    tabWidth: 4
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
languages:
  en:
    languagename: English
    menu:
      main:
        - name: About me
          weight: 1
          url: about/
        - name: Blog
          weight: 2
          url: posts/
params:
  author: Federico Barcelona
  description: Federico Barcelona's personal website
  keywords: 'blog,developer,personal,devops'
  info: DevOps & Product Integration Engineer at Sysdig
  avatarurl: images/fede.jpg
  footercontent: ''
  dateformat: 'January 2, 2006'
  hideFooter: true
  hideCredits: true
  hideCopyright: false
  since: 2020
  rtl: false
  # Specify light/dark colorscheme
  # Supported values:
  # "auto" (use preference set by browser)
  # "dark" (dark background, light foreground)
  # "light" (light background, dark foreground) (default)
  colorscheme: auto
  # Hide the toggle button, along with the associated vertical divider
  hidecolorschemetoggle: false
  # Series see also post count
  maxSeeAlsoItems: 5
  # Enable Twemoji
  enableTwemoji: true
  # Custom CSS
  customCSS: []
  # Custom SCSS
  customSCSS: []
  # Custom JS
  customJS: []

  # If you want to use fathom(https://usefathom.com) for analytics, add this section
  # fathomAnalytics:
  #   siteID: "ABCDE"
  #   # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
  #   serverURL: "analytics.example.com"

  # If you want to use plausible(https://plausible.io) for analytics, add this section
  # plausibleAnalytics:
  #   domain: "example.com"
  #   # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
  #   serverURL: "analytics.example.com"

  # If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
  # goatCounter:
  #   code: "code"

  social:
    - name: Github
      icon: fa fa-github
      weight: 1
      url: 'https://github.com/tembleking/'
    - name: Gitlab
      icon: fa fa-gitlab
      weight: 2
      url: 'https://gitlab.com/tembleking/'
    - name: Twitter
      icon: fa fa-twitter
      weight: 3
      url: 'https://twitter.com/tembleking/'
    - name: LinkedIn
      icon: fa fa-linkedin
      weight: 4
      url: 'https://www.linkedin.com/in/fede-barcelona/'
